{.$DEFINE MM_BUCKETMM}
{.$DEFINE MM_DKCIA32}
{$DEFINE MM_FASTMM2}
{.$DEFINE MM_FASTMM3}
{.$DEFINE MM_FASTMM4}
{.$DEFINE MM_RTLMM}
{.$DEFINE MM_WINMEM}
//{.$DEFINE MM_EWCMM}        // disabled...Fails
//{.$DEFINE MM_NEXUSMM}      // disabled...Fails
//{.$DEFINE MM_BUCKETMM_ASM} // disabled...Fails
//{.$DEFINE MM_TOPMM}        // disabled...Fails
//{.$DEFINE MM_RECYCLERMM}   // disabled...Fails
//{.$DEFINE MM_MULTIMM}      // disabled...Fails
//{.$DEFINE MM_QMEMORY}      // disabled...Fails
//{.$DEFINE MM_PSDMM}        // disabled...deprecated
//{.$DEFINE MM_LOCALHEAP}    // disabled... identical to WINMEM
//{.$DEFINE MM_HEAPMM}       // disabled... identical to WINMEM


